# config
cover: /img/bg_img.jpg
logo: /img/logo.png
top_saying:
  - title: Eileen Yu
  - content: Pursuing knowledge
bottom_saying: Rule the world ASA finish one more line of code.
# Content
excerpt_link: Read More

rss: /atom.xml

# highlightjs: vs
highlightjs: dracula

#Works
works:
  - works_name: LFX 22 Fall Kyverno
    works_url: https://kyverno.io/docs/writing-policies/exceptions/
  - works_name: GSoC 22 GitLab
    works_url:
      https://gitlab.com/gitlab-org/security-products/package-hunter
      # - works_name: BBB
      # works_url: /atom.xml

#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/Eileen-Yu
twitter:
  https://twitter.com/eil7007
  # facebook: https://www.facebook.com/
linkedin: https://www.linkedin.com/in/eileen-yu/
weibo: https://www.weibo.com/eileen7070

#about  timeline
timeline:
  - num: 1
    word: 2014/06/12-Start
  - num: 2
    word: 2014/11/29-XXX
  - num: 3
    word: 2015/02/18-DDD
  - num: 4
    word: More

#Links
links:
#- name: Kieran
#link: http://go.kieran.top/
# - name: Name
# link: http://domain.com/

# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: false
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 2
